config/routes.rb
Rails.application.routes.draw do
  resources :simple_chores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simple_chore.rb
class SimpleChore < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/simple_chores_controller.rb
class SimpleChoresController < ApplicationController
  before_action :set_simple_chore, only: [:show, :edit, :update, :destroy]

  # GET /simple_chores
  # GET /simple_chores.json
  def index
    @simple_chores = SimpleChore.all
    respond_to do |format|
      format.html
      format.json { render :json => @simple_chores }
    end
  end

  # GET /simple_chores/1
  # GET /simple_chores/1.json
  def show
  end

  # GET /simple_chores/new
  def new
    @simple_chore = SimpleChore.new
  end

  # GET /simple_chores/1/edit
  def edit
  end

  # POST /simple_chores
  # POST /simple_chores.json
  def create
    @simple_chore = SimpleChore.new(simple_chore_params)

    respond_to do |format|
      if @simple_chore.save
        format.html { redirect_to @simple_chore, notice: 'Simple chore was successfully created.' }
        format.json { render :show, status: :created, location: @simple_chore }
      else
        format.html { render :new }
        format.json { render json: @simple_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simple_chores/1
  # PATCH/PUT /simple_chores/1.json
  def update
    respond_to do |format|
      if @simple_chore.update(simple_chore_params)
        format.html { redirect_to @simple_chore, notice: 'Simple chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @simple_chore }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @simple_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_chores/1
  # DELETE /simple_chores/1.json
  def destroy
    @simple_chore.destroy
    respond_to do |format|
      format.html { redirect_to simple_chores_url, notice: 'Simple chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simple_chore
      @simple_chore = SimpleChore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simple_chore_params
      params.require(:simple_chore).permit(:name, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_chores_helper.rb
module SimpleChoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueDebuggingExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_chores/_form.html.erb
<%= form_with(model: simple_chore, local: true) do |form| %>
  <% if simple_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(simple_chore.errors.count, "error") %> prohibited this simple_chore from being saved:</h2>

      <ul>
      <% simple_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :simple_chore_name %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :simple_chore_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/simple_chores/edit.html.erb
<h1>Editing Simple Chore</h1>

<%= render 'form', simple_chore: @simple_chore %>

<%= link_to 'Show', @simple_chore %> |
<%= link_to 'Back', simple_chores_path %>

app/views/simple_chores/index.html.erb
<script type="text/javascript">
  initialize()
</script>

<p id="notice"><%= notice %></p>

<h1>Simple Chores</h1>
  <div id='chores_list'>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <keep-alive>
    <tr is='chore-row' 
      v-for="chore in chores" 
      v-bind:chore="chore"
      :key='chore.id'>  
    </tr>
  </keep-alive>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Simple Chore', new_simple_chore_path %>

<!-- Defining Vue templates to work with components -->
<script type="text/x-template" id="chore-row">
    <tr>
      <td>{{ chore.name }}</td>
      <td>{{ chore.completed }}</td>
      <td v-on:click="toggle_complete(chore)">Check</td>
      <td v-on:click="remove_record(chore)">Delete</td>
    </tr>
</script>

app/views/simple_chores/new.html.erb
<h1>New Simple Chore</h1>

<%= render 'form', simple_chore: @simple_chore %>

<%= link_to 'Back', simple_chores_path %>

app/views/simple_chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @simple_chore.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @simple_chore.completed %>
</p>

<%= link_to 'Edit', edit_simple_chore_path(@simple_chore) %> |
<%= link_to 'Back', simple_chores_path %>